### ISSUE TITLE
Execution error ...

### ISSUE THREAD

**Issue by lgs777** [Megalan/PatreonDownloader#10]
I succeeded in downloading the file through the first released file. However, from the second attempt, this error message appears. Plz help!

PatreonDownloader.app --creator #vinectschwenk --download-directory c:\downloadss --descriptions --embeds

2020-05-13 01:04:32.7909 INFO Retrieving cookies...
2020-05-13 01:05:16.4248 INFO Preparing to download...
2020-05-13 01:05:17.7809 INFO Retrieving campaign information...
2020-05-13 01:05:20.3790 FATAL Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.PatreonDownloaderException: Unable to retrieve campaign id
   at PatreonDownloader.Engine.PatreonDownloader.Download(String creatorName, PatreonDownloaderSettings settings) in C:\Users\jeong\Downloads\PatreonDownloader-dev\PatreonDownloader-dev\PatreonDownloader.Engine\PatreonDownloader.cs:line 162
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in C:\Users\jeong\Downloads\PatreonDownloader-dev\PatreonDownloader-dev\PatreonDownloader.App\Program.cs:line 136
   at PatreonDownloader.App.Program.Main(String[] args) in C:\Users\jeong\Downloads\PatreonDownloader-dev\PatreonDownloader-dev\PatreonDownloader.App\Program.cs:line 58

**Comment by Megalan** [comment]
You are not supplying a valid creator name.

The creator name is a part of their page url:
https://www.patreon.com/ **CREATOR'S NAME IS IN THIS PART OF THE URL** /posts

**Comment by lgs777** [comment]
no. The creator's name is correct. I checked it again and again, but the symptoms are the same .....
https://www.patreon.com/vincentschwenk/posts

**Comment by Megalan** [comment]
I can only help you if you provide me information I asked you about in #6.

If you decide to follow steps described in #6, please use #6 for further discussion. Otherwise I kindly ask you to stop creating any more issues because I can't help you if you won't cooperate with me.

**Comment by lgs777** [comment]
Sorry! I wasn't familiar with using GITHUB, so I was late to check this article. I thought this was deleted.
I uploaded a file to a post. Thank you for your kind response to the issue.
