### ISSUE TITLE
Fatal Error: CookieValidationException

### ISSUE THREAD

**Issue by Grygon** [Megalan/PatreonDownloader#4]
Receiving the following error:

PS C:\Users\Grygon\Documents\PatreonDownloader\PatreonDownloader.App> dotnet run --creator XXXXX --download-directory c:\patron-downloads --descriptions --embeds --campaign-images --json
2020-02-15 21:14:09.2670 INFO Retrieving cookies...
2020-02-15 21:14:12.3122 INFO Preparing to download...
2020-02-15 21:14:12.3411 FATAL Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.CookieValidationException: __ssid cookie not found
   at PatreonDownloader.Engine.Stages.Initialization.CookieValidator.ValidateCookies(CookieContainer cookieContainer) in C:\Users\Grygon\Documents\PatreonDownloader\PatreonDownloader.Engine\Stages\Initialization\CookieValidator.cs:line 34
   at PatreonDownloader.Engine.PatreonDownloader.Download(String creatorName, PatreonDownloaderSettings settings) in C:\Users\Grygon\Documents\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 114
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, PatreonDownloaderSettings settings) in C:\Users\Grygon\Documents\PatreonDownloader\PatreonDownloader.App\Program.cs:line 131
   at PatreonDownloader.App.Program.Main(String[] args) in C:\Users\Grygon\Documents\PatreonDownloader\PatreonDownloader.App\Program.cs:line 55

Tried to run app, then log in. I see the window loading (with the logged-in view) each time I run it, then it crashes.

**Comment by Megalan** [comment]
Interesting. I wonder if this cookie is not required. 

Please do the following:
1) Open C:\Users\Grygon\Documents\PatreonDownloader\PatreonDownloader.Engine\Stages\Initialization\CookieValidator.cs
2) Remove the following lines:
`if (cookies["__ssid"] == null)`
`throw new CookieValidationException("__ssid cookie not found");`
3) Run it again and see if it works for you. If it works then I'll remove this check from the code.

**Comment by Megalan** [comment]
I am closing this issue as more than a week has passed without an answer.

**Comment by DeastinY** [comment]
Hi there, 
just ran into this exact issue and removing the suggested lines fixed it for me 👍

**Comment by Megalan** [comment]
Alright, thank you for testing. I have removed this line from the code.
