### ISSUE TITLE
Unable to retrieve campaign id

### ISSUE THREAD

**Issue by Leon298** [Megalan/PatreonDownloader#5]
Using all variations of PatreonDownloader.App.exe --creator *CreatorName* alone or to dl everything we get

2020-02-15 23:12:54.8364 FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.PatreonDownloaderException: Unable to retrieve campaign id: Unable to download from https://www.patreon.com/xxxx/posts: Response status code does not indicate success: 403 (Forbidden). ---> PatreonDownloader.Engine.Exceptions.DownloadException: Unable to download from https://www.patreon.com/xxxx/posts: Response status code does not indicate success: 403 (Forbidden). ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at PatreonDownloader.Engine.WebDownloader.DownloadString(String url) in D:\Desktop\PatreonDownloader-dev\PatreonDownloader.Engine\WebDownloader.cs:line 75
   --- End of inner exception stack trace ---
   at PatreonDownloader.Engine.WebDownloader.DownloadString(String url) in D:\Desktop\PatreonDownloader-dev\PatreonDownloader.Engine\WebDownloader.cs:line 79
   at PatreonDownloader.Engine.Stages.Crawling.CampaignIdRetriever.RetrieveCampaignId(String url) in D:\Desktop\PatreonDownloader-dev\PatreonDownloader.Engine\Stages\Crawling\CampaignIdRetriever.cs:line 33
   --- End of inner exception stack trace ---
   at PatreonDownloader.Engine.Stages.Crawling.CampaignIdRetriever.RetrieveCampaignId(String url) in D:\Desktop\PatreonDownloader-dev\PatreonDownloader.Engine\Stages\Crawling\CampaignIdRetriever.cs:line 46
   at PatreonDownloader.Engine.PatreonDownloader.Download(String creatorName, PatreonDownloaderSettings settings) in D:\Desktop\PatreonDownloader-dev\PatreonDownloader.Engine\PatreonDownloader.cs:line 149
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, PatreonDownloaderSettings settings) in D:\Desktop\PatreonDownloader-dev\PatreonDownloader.App\Program.cs:line 131
   at PatreonDownloader.App.Program.Main(String[] args) in D:\Desktop\PatreonDownloader-dev\PatreonDownloader.App\Program.cs:line 55

**Comment by Megalan** [comment]
Thank you for your report. This is a result of cloudflare anti-bot protection being too aggressive. I'm trying to figure out how to fool it.

Please use #3 for further tracking and discussion of this problem.
