### ISSUE TITLE
i can not get this to work

### ISSUE THREAD

**Issue by mightyonion** [Megalan/PatreonDownloader#9]
i have no coding experience and next to no knowledge with any of this so it could just be my own ignorance but i cannot get this to work at all. i am constantly getting fatal errors every time i try to run it.

i try this in command line

"dotnet run --creator https://www.patreon.com/*creator*/posts --download-directory D:\pat down\downloads"

and get this error

2020-05-10 10:59:04.7814 FATAL Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.PatreonDownloaderException: Unable to retrieve campaign id
   at PatreonDownloader.Engine.PatreonDownloader.Download(String creatorName, PatreonDownloaderSettings settings) in D:\pat down\PatreonDownloader-0.9.1.1\PatreonDownloader.Engine\PatreonDownloader.cs:line 162
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in D:\pat down\PatreonDownloader-0.9.1.1\PatreonDownloader.App\Program.cs:line 136
   at PatreonDownloader.App.Program.Main(String[] args) in D:\pat down\PatreonDownloader-0.9.1.1\PatreonDownloader.App\Program.cs:line 58

i have no clue what im doing wrong please help my noobish ass.

and i've tried running it as a .exe but the window closes as soon as it opens.

**Comment by Megalan** [comment]
The --creator argument accepts creator name, not url. 
The creator's name is indicated in bold:
https://www.patreon.com/ **CREATOR'S NAME IS IN THIS PART OF THE URL** /posts

**Comment by mightyonion** [comment]
Figured it would be my own stupidity, it's working fine now thanks for the quick response.
